### ISSUE TITLE
Partition training data

### ISSUE THREAD

**Issue by ksuderman** [lappsgrid-incubator/galaxy-paper-rank#11]
Set up a system/program to partition the training data (see #1 and #10) into *k* partitions so we can perform k-fold validation runs.

**Inputs**
1. *k* - the number of partitions to generate
1. *n* - the total size of the generated evaluation set
1. a directory of files containing positive examples
1. a directory of files containing negative examples
1. the output directory to write results.

**Outputs**
1. *k* files in the output directory, each with *n*/*k* file IDs

**Notes**
If *n* < |training set| then print a warning and generate the *k* partitions using the entire training set.
else select *n* documents at random from the entire training set.

**Comment by ksuderman** [comment]
Part of #5

**Comment by nancyide** [comment]
No need to do this if using BERT. Should get rid of this task.
