### ISSUE TITLE
Upload Elsevier articles to Lapps server

### ISSUE THREAD

**Issue by ksuderman** [lappsgrid-incubator/galaxy-paper-rank#8]
Put pdf files in `/data/corpora/curation/gold/pdf/elsevier`
Put xml files in `/data/corpora/curation/gold/xml/elsevier`

Extract txt files will go into `/data/corpora/curation/gold/txt/elsevier`

**Comment by nmajumder1** [comment]
There is no directory "elsevier" under /data/corpora/curation/gold/xml/ and I am unable to create a directory in that specific folder.

**Comment by nmajumder1** [comment]
Thank you for changing the permissions, I was able to put all the Elsevier files under the specified directory.
